"""add candidate_name and job_title to interviews

Revision ID: 1996bd38d50a
Revises: 381dc9efa726
Create Date: 2025-09-09 20:33:40.730309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1996bd38d50a'
down_revision: Union[str, Sequence[str], None] = '381dc9efa726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('candidate_name', sa.Text(), nullable=False))
    op.add_column('interviews', sa.Column('job_title', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'job_title')
    op.drop_column('interviews', 'candidate_name')
    # ### end Alembic commands ###
