"""Add job_title and candidate_name columns to matches table

Revision ID: 381dc9efa726
Revises: c3849395937a
Create Date: 2025-09-08 17:29:51.182534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '381dc9efa726'
down_revision: Union[str, Sequence[str], None] = 'c3849395937a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('job_title', sa.Text(), nullable=False))
    op.add_column('matches', sa.Column('candidate_name', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'candidate_name')
    op.drop_column('matches', 'job_title')
    # ### end Alembic commands ###
