"""create user table for auth

Revision ID: 820d6fa100c3
Revises: 1996bd38d50a
Create Date: 2025-09-13 11:18:54.005229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '820d6fa100c3'
down_revision: Union[str, Sequence[str], None] = '1996bd38d50a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'candidates', 'users', ['user_id'], ['id'])
    op.add_column('interviews', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'interviews', 'users', ['user_id'], ['id'])
    op.add_column('jobs', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'jobs', 'users', ['user_id'], ['id'])
    op.add_column('matches', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'matches', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_column('matches', 'user_id')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'user_id')
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.drop_column('interviews', 'user_id')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'user_id')
    # ### end Alembic commands ###
