"""remove unique email requirement for jobs

Revision ID: cd2169376437
Revises: 820d6fa100c3
Create Date: 2025-09-13 23:40:33.422113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd2169376437'
down_revision: Union[str, Sequence[str], None] = '820d6fa100c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=True)
    # ### end Alembic commands ###
