"""Add reasoning, missing_experience, missing_education to matches

Revision ID: f09e94edccb9
Revises: acd518fb7764
Create Date: 2025-09-03 18:49:36.957240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f09e94edccb9'
down_revision: Union[str, Sequence[str], None] = 'acd518fb7764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('reasoning', sa.Text(), nullable=False))
    op.add_column('matches', sa.Column('missing_experience', sa.Text(), nullable=True))
    op.add_column('matches', sa.Column('missing_education', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'missing_education')
    op.drop_column('matches', 'missing_experience')
    op.drop_column('matches', 'reasoning')
    # ### end Alembic commands ###
